/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f6fafe',
        'primary': '#00429d',
        'primary-fixed': '#d9e2ff',
        'primary-fixed-dim': '#b0c6ff',
        'primary-container': '#0a58ca',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#001945',
        'on-primary-fixed-variant': '#00419d',
        'on-surface': '#171c1f',
        'on-surface-variant': '#424653',
        'surface': '#f6fafe',
        'surface-dim': '#d6dade',
        'surface-container': '#eaeef2',
        'surface-container-low': '#f0f4f8',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#e4e9ed',
        'surface-container-highest': '#dfe3e7',
        'surface-variant': '#dfe3e7',
        'secondary': '#505f76',
        'secondary-container': '#d0e1fb',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#54647a',
        'tertiary': '#7f2b00',
        'tertiary-fixed': '#ffdbce',
        'tertiary-fixed-dim': '#ffb599',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#370e00',
        'outline': '#737785',
        'outline-variant': '#c3c6d6',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#2c3134',
        'inverse-on-surface': '#edf1f5',
        'inverse-primary': '#b0c6ff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
